import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';
import { palette } from './colors';

const fontConfig = {
  fontFamily: 'System',
};

const fonts = configureFonts({ config: fontConfig });

export const lightTheme = {
  ...MD3LightTheme,
  dark: false,
  fonts,
  colors: {
    ...MD3LightTheme.colors,
    primary: palette.darkBlue,
    primaryContainer: '#E8EAF6',
    onPrimaryContainer: palette.darkBlue,
    secondary: palette.gold,
    secondaryContainer: '#FFF8E1',
    onSecondaryContainer: '#4E3B00',
    tertiary: palette.amber,
    tertiaryContainer: '#FFF3E0',
    onTertiaryContainer: '#5C2E00',
    surface: palette.surfaceLight,
    surfaceVariant: palette.gray50,
    onSurface: palette.black,
    onSurfaceVariant: palette.gray700,
    background: palette.backgroundLight,
    onBackground: palette.black,
    outline: palette.gray300,
    outlineVariant: palette.gray200,
    elevation: {
      level0: 'transparent',
      level1: palette.white,
      level2: palette.gray50,
      level3: palette.gray100,
      level4: palette.gray100,
      level5: palette.gray200,
    },
    error: palette.error,
    errorContainer: '#FFEBEE',
    onError: palette.white,
    inverseSurface: palette.gray900,
    inverseOnSurface: palette.gray100,
    inversePrimary: palette.goldLight,
    shadow: 'rgba(0,0,0,0.1)',
    scrim: 'rgba(0,0,0,0.3)',
    backdrop: 'rgba(0,0,0,0.5)',
  },
  roundness: 16,
  custom: {
    glassBg: 'rgba(255,255,255,0.7)',
    glassBorder: 'rgba(255,255,255,0.3)',
    glassShadow: 'rgba(0,0,0,0.08)',
    cardElevation: 2,
    gradientStart: palette.darkBlue,
    gradientEnd: palette.deepBlue,
    statusUpcoming: palette.gray400,
    statusOngoing: palette.success,
    statusCompleted: palette.gray300,
    goldGradient: [palette.gold, palette.goldLight],
    facultyColors: {
      Jerusalen: '#D32F2F',
      Antioquia: '#1976D2',
      Berea: '#388E3C',
      Efeso: '#F57C00',
      Galilea: '#7B1FA2',
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  dark: true,
  fonts,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#5C9EFF',
    primaryContainer: '#1A237E',
    onPrimaryContainer: '#C5CAE9',
    secondary: palette.gold,
    secondaryContainer: '#4E3B00',
    onSecondaryContainer: '#FFF8E1',
    tertiary: palette.amberLight,
    tertiaryContainer: '#5C2E00',
    onTertiaryContainer: '#FFF3E0',
    surface: palette.surfaceDark,
    surfaceVariant: '#1E1E1E',
    onSurface: '#E0E0E0',
    onSurfaceVariant: palette.gray400,
    background: palette.backgroundDark,
    onBackground: '#E0E0E0',
    outline: palette.gray600,
    outlineVariant: '#2A2A2A',
    elevation: {
      level0: 'transparent',
      level1: '#1A1A1A',
      level2: '#242424',
      level3: '#2A2A2A',
      level4: '#2E2E2E',
      level5: '#333333',
    },
    error: '#EF5350',
    errorContainer: '#4A1C1C',
    onError: palette.black,
    inverseSurface: palette.gray100,
    inverseOnSurface: palette.gray800,
    inversePrimary: palette.darkBlue,
    shadow: 'rgba(0,0,0,0.5)',
    scrim: 'rgba(0,0,0,0.6)',
    backdrop: 'rgba(0,0,0,0.8)',
  },
  roundness: 16,
  custom: {
    glassBg: 'rgba(0,0,0,0.45)',
    glassBorder: 'rgba(255,255,255,0.06)',
    glassShadow: 'rgba(0,0,0,0.4)',
    cardElevation: 2,
    gradientStart: '#0D1B4A',
    gradientEnd: '#0A0E2A',
    statusUpcoming: palette.gray500,
    statusOngoing: '#66BB6A',
    statusCompleted: palette.gray600,
    goldGradient: [palette.gold, palette.goldLight],
    facultyColors: {
      Jerusalen: '#D32F2F',
      Antioquia: '#1976D2',
      Berea: '#388E3C',
      Efeso: '#F57C00',
      Galilea: '#7B1FA2',
    },
  },
};

export type AppTheme = typeof lightTheme;
